name: CI Pipeline for Python and Java

on:
  push:
    branches: ["main"]

jobs:
  # Python Job
  python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Python Syntax Check
        run: python -m compileall .
      - name: Run Unit Tests
        run: python3 -m unittest discover
      - name: Run Integration Tests
        run: pytest tests/integration_tests.py  # Example integration tests

  # Java Job
  java:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
      - name: Install Maven
        run: sudo apt-get install maven
      - name: Run Java Syntax Check
        run: javac $(find . -name "*.java")
      - name: Run Java Unit Tests
        run: mvn test
      - name: Run Integration Tests
        run: mvn verify  # Example integration tests with Maven
