name: CI Pipeline for Python and Java

on:
  push:
    branches: ["main"]

jobs:
  # Python Job
  python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest  # Install pytest
      - name: Run Python Syntax Check
        run: python -m compileall .
      - name: Run Unit Tests
        run: python3 -m unittest discover
      - name: Run Integration Tests
        run: |
          pytest tests/  # Adjusted to run all tests in the "tests" directory

  # Java Job
  java:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Download JUnit JAR (JUnit 5 example)
        run: |
          wget https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.7.2/junit-platform-console-standalone-1.7.2.jar
      - name: Compile Java Code
        run: javac $(find . -name "*.java")
      - name: Run Java Unit Tests
        run: |
          java -cp .:junit-platform-console-standalone-1.7.2.jar org.junit.platform.console.ConsoleLauncher --scan-classpath
